overrides:
  '@babel/core@<=7.29.0': ^7.29.1
  brace-expansion: ^5.0.9
  fast-uri: ^3.1.5
  nanoid@<3.3.16: ^3.3.16
  nanoid@<3.3.18: ^3.3.18
  postcss@<=8.5.17: ^8.5.18
  postcss@<=8.5.22: ^8.5.23
  react-router@>=6.0.0 <7.18.0: ^7.18.0
  react-router@>=6.4.0 <7.18.0: ^7.18.0
  react-router@>=7.0.0 <7.18.0: ^7.18.0
  react-router@>=7.11.0 <7.18.0: ^7.18.0
  react-router@>=7.12.0 <7.18.2: ^7.18.2
  vite@>=8.0.0 <=8.0.15: ^8.0.16

minimumReleaseAge: 10080

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - vite@8.0.16
  - '@babel/core@7.29.1'
  - brace-expansion@5.0.7
  - fast-uri@3.1.4
  - react-router@7.18.0
  - brace-expansion@5.0.8
  - postcss@8.5.23
  - fast-uri@3.1.5
  - brace-expansion@5.0.9
  - react-router@7.18.2
  - nanoid@3.3.16
  - nanoid@3.3.18
  - postcss@8.5.18
  - fast-uri@3.1.3
